INSERT INTO users(
    first_name,
    last_name,
    username,
    password,
    phoneNumber)
    VALUES 
    (
        'Oswaldo',
        'Almazo',
        'halo123u',
        'hello',
        6666
    ),
    (
        'David',
        'Hernandez',
        'ampharos',
        'hello2',
        1111
    ),
    (
        'Danielle',
        'Vannucci',
        'daniven',
        'hello3',
        2222
    ) 
